version: "3.7"
services:
  master01:
    image: centos:hadoop
    privileged: true
    container_name: master01
    hostname: master01
    volumes:
     - type: bind
       source: /home/malachai/hadoop-ecosystem/keys
       target: /root/.ssh
    networks:
      cluster-net:
        ipv4_address: 172.16.238.2
    ports:
      - "9870:9870"
    extra_hosts:
      - "master02:172.16.238.3"
      - "slave01:172.16.238.4"
      - "slave02:172.16.238.5"
      - "slave03:172.16.238.6"
    stdin_open: true
    tty: true

  master02:
    image: centos:hadoop
    privileged: true
    container_name: master02
    hostname: master02
    volumes:
     - type: bind
       source: /home/malachai/hadoop-ecosystem/keys
       target: /root/.ssh
    networks:
      cluster-net:
        ipv4_address: 172.16.238.3
    extra_hosts:
      - "master01:172.16.238.2"
      - "slave01:172.16.238.4"
      - "slave02:172.16.238.5"
      - "slave03:172.16.238.6"
    stdin_open: true
    tty: true

  slave01:
    image: centos:hadoop
    privileged: true
    container_name: slave01
    hostname: slave01
    volumes:
     - type: bind
       source: /home/malachai/hadoop-ecosystem/keys
       target: /root/.ssh
    networks:
      cluster-net:
        ipv4_address: 172.16.238.4
    extra_hosts:
      - "master01:172.16.238.2"
      - "master02:172.16.238.3"
      - "slave02:172.16.238.5"
      - "slave03:172.16.238.6"
    stdin_open: true
    tty: true

  slave02:
    image: centos:hadoop
    privileged: true
    container_name: slave02
    hostname: slave02
    volumes:
     - type: bind
       source: /home/malachai/hadoop-ecosystem/keys
       target: /root/.ssh
    networks:
      cluster-net:
        ipv4_address: 172.16.238.5
    extra_hosts:
      - "master01:172.16.238.2"
      - "master02:172.16.238.3"
      - "slave01:172.16.238.4"
      - "slave03:172.16.238.6"
    stdin_open: true
    tty: true

  slave03:
    image: centos:hadoop
    privileged: true
    container_name: slave03
    hostname: slave03
    volumes:
     - type: bind
       source: /home/malachai/hadoop-ecosystem/keys
       target: /root/.ssh
    networks:
      cluster-net:
        ipv4_address: 172.16.238.6
    extra_hosts:
      - "master01:172.16.238.2"
      - "master02:172.16.238.3"
      - "slave01:172.16.238.4"
      - "slave02:172.16.238.5"
    stdin_open: true
    tty: true

networks:
  cluster-net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"

