version: "3.7"
services:
  master01:
    build:
      context: /home/malachai/hadoop-ecosystem/centos7-hadoop-ha/spark/myid
      args:
        - MYID=1
    privileged: true
    container_name: master01
    hostname: master01
    volumes:
     - type: bind
       source: /home/malachai/hadoop-ecosystem/keys
       target: /root/.ssh
     - type: bind
       source: /home/malachai/hadoop-ecosystem/centos7-hadoop-ha/airflow/dags
       target: /opt/airflow/current/dags
     - type: bind
       source: /home/malachai/hadoop-ecosystem/centos7-hadoop-ha/airflow/logs
       target: /opt/airflow/current/logs
    networks:
      cluster-net:
        ipv4_address: 172.16.238.2
    ports:
      - "9870:9870"
      - "8088:8088"
      - "8042:8042"
      - "50070:50070"
      - "19888:19888"
      - "18080:18080"
      - "4040:4040"
      - "8090:8090"
    extra_hosts:
      - "master02:172.16.238.3"
      - "slave01:172.16.238.4"
      - "slave02:172.16.238.5"
      - "slave03:172.16.238.6"
    stdin_open: true
    tty: true

  master02:
    build:
      context: /home/malachai/hadoop-ecosystem/centos7-hadoop-ha/spark/myid
      args:
        - MYID=2
    privileged: true
    container_name: master02
    hostname: master02
    volumes:
     - type: bind
       source: /home/malachai/hadoop-ecosystem/keys
       target: /root/.ssh
     - type: bind
       source: /home/malachai/hadoop-ecosystem/centos7-hadoop-ha/airflow/dags
       target: /opt/airflow/current/dags
     - type: bind
       source: /home/malachai/hadoop-ecosystem/centos7-hadoop-ha/airflow/logs
       target: /opt/airflow/current/logs
    networks:
      cluster-net:
        ipv4_address: 172.16.238.3
    ports:
      - "9871:9870"
      - "8089:8088"
      - "8043:8042"
      - "50071:50070"
      - "19889:19888"
      - "18081:18081"
      - "4041:4040"
      - "8091:8090"
    extra_hosts:
      - "master01:172.16.238.2"
      - "slave01:172.16.238.4"
      - "slave02:172.16.238.5"
      - "slave03:172.16.238.6"
    stdin_open: true
    tty: true

  slave01:
    build:
      context: /home/malachai/hadoop-ecosystem/centos7-hadoop-ha/rabbitmq/myid
      args:
        - MYID=3
    privileged: true
    container_name: slave01
    hostname: slave01
    volumes:
     - type: bind
       source: /home/malachai/hadoop-ecosystem/keys
       target: /root/.ssh
     - type: bind
       source: /home/malachai/hadoop-ecosystem/centos7-hadoop-ha/airflow/dags
       target: /opt/airflow/current/dags
     - type: bind
       source: /home/malachai/hadoop-ecosystem/centos7-hadoop-ha/airflow/logs
       target: /opt/airflow/current/logs
    networks:
      cluster-net:
        ipv4_address: 172.16.238.4
    ports:
      - "5082:5080"
      - "5557:5555"
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "15672:15672"
      - "25672:25672"
      - "61613:61613"
      - "61614:61614"
      - "1883:1883"
      - "8883:8883"
    extra_hosts:
      - "master01:172.16.238.2"
      - "master02:172.16.238.3"
      - "slave02:172.16.238.5"
      - "slave03:172.16.238.6"
    stdin_open: true
    tty: true

  slave02:
    image: centos7/hadoop:ha
    privileged: true
    container_name: slave02
    hostname: slave02
    volumes:
     - type: bind
       source: /home/malachai/hadoop-ecosystem/keys
       target: /root/.ssh
     - type: bind
       source: /home/malachai/hadoop-ecosystem/centos7-hadoop-ha/airflow/dags
       target: /opt/airflow/current/dags
     - type: bind
       source: /home/malachai/hadoop-ecosystem/centos7-hadoop-ha/airflow/logs
       target: /opt/airflow/current/logs
    networks:
      cluster-net:
        ipv4_address: 172.16.238.5
    extra_hosts:
      - "master01:172.16.238.2"
      - "master02:172.16.238.3"
      - "slave01:172.16.238.4"
      - "slave03:172.16.238.6"
    stdin_open: true
    tty: true

  slave03:
    image: centos7/hadoop/flume:ha
    privileged: true
    container_name: slave03
    hostname: slave03
    volumes:
     - type: bind
       source: /home/malachai/hadoop-ecosystem/keys
       target: /root/.ssh
     - type: bind
       source: /home/malachai/hadoop-ecosystem/centos7-hadoop-ha/airflow/dags
       target: /opt/airflow/current/dags
     - type: bind
       source: /home/malachai/hadoop-ecosystem/centos7-hadoop-ha/airflow/logs
       target: /opt/airflow/current/logs
    networks:
      cluster-net:
        ipv4_address: 172.16.238.6
    extra_hosts:
      - "master01:172.16.238.2"
      - "master02:172.16.238.3"
      - "slave01:172.16.238.4"
      - "slave02:172.16.238.5"
    stdin_open: true
    tty: true

networks:
  cluster-net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"

